### ISSUE TITLE
EventDection.m debug

### ISSUE THREAD

**Issue by want2bedoctor** [wojtusch/HuMoD#1]
I tried to use the original code of 'EventDection.m' but it didn't work well.
I think the row 487~508 had indexing errors.

I suggest you to change the row 487~508 like below

      
` % Plot joints
        plot3d(handles.motion.jointX.estimated(:, index), handles.motion.jointY.estimated(:, index), handles.motion.jointZ.estimated(:, index), 'b*');

        % Plot head
        plot3d([handles.motion.jointX.estimated(1, index), handles.motion.surfaceX(1, index), handles.motion.surfaceX(2, index), handles.motion.jointX.estimated(1, index)], [handles.motion.jointY.estimated(1, index), handles.motion.surfaceY(1, index), handles.motion.surfaceY(2, index), handles.motion.jointY.estimated(1, index)], [handles.motion.jointZ.estimated(1, index), handles.motion.surfaceZ(1, index), handles.motion.surfaceZ(2, index), handles.motion.jointZ.estimated(1, index)], 'k');

        % Plot left arm
        plot3d([handles.motion.jointX.estimated(1, index), handles.motion.jointX.estimated(2, index), handles.motion.jointX.estimated(4, index), handles.motion.markerX(8, index)], [handles.motion.jointY.estimated(1, index), handles.motion.jointY.estimated(2, index), handles.motion.jointY.estimated(4, index), handles.motion.markerY(8, index)], [handles.motion.jointZ.estimated(1, index), handles.motion.jointZ.estimated(2, index), handles.motion.jointZ.estimated(4, index), handles.motion.markerZ(8, index)], 'k');

        % Plot right arm
        plot3d([handles.motion.jointX.estimated(1, index), handles.motion.jointX.estimated(3, index), handles.motion.jointX.estimated(5, index), handles.motion.markerX(9, index)], [handles.motion.jointY.estimated(1, index), handles.motion.jointY.estimated(3, index), handles.motion.jointY.estimated(5, index), handles.motion.markerY(9, index)], [handles.motion.jointZ.estimated(1, index), handles.motion.jointZ.estimated(3, index), handles.motion.jointZ.estimated(5, index), handles.motion.markerZ(9, index)], 'k');

        % Plot spinal
        plot3d([handles.motion.jointX.estimated(7, index), handles.motion.jointX.estimated(6, index), handles.motion.jointX.estimated(1, index)], [handles.motion.jointY.estimated(7, index), handles.motion.jointY.estimated(6, index), handles.motion.jointY.estimated(1, index)], [handles.motion.jointZ.estimated(7, index), handles.motion.jointZ.estimated(6, index), handles.motion.jointZ.estimated(1, index)], 'k');

        % Plot pelvis
        plot3d([handles.motion.jointX.estimated(7, index), handles.motion.jointX.estimated(8, index), handles.motion.jointX.estimated(9, index), handles.motion.jointX.estimated(7, index)], [handles.motion.jointY.estimated(7, index), handles.motion.jointY.estimated(8, index), handles.motion.jointY.estimated(9, index), handles.motion.jointY.estimated(7, index)], [handles.motion.jointZ.estimated(7, index), handles.motion.jointZ.estimated(8, index), handles.motion.jointZ.estimated(9, index), handles.motion.jointZ.estimated(7, index)], 'k');

        % Plot left leg
        plot3d([handles.motion.jointX.estimated(14, index), handles.motion.jointX.estimated(12, index), handles.motion.jointX.estimated(10, index), handles.motion.jointX.estimated(8, index)], [handles.motion.jointY.estimated(14, index), handles.motion.jointY.estimated(12, index), handles.motion.jointY.estimated(10, index), handles.motion.jointY.estimated(8, index)], [handles.motion.jointZ.estimated(14, index), handles.motion.jointZ.estimated(12, index), handles.motion.jointZ.estimated(10, index), handles.motion.jointZ.estimated(8, index)], 'r');

        % Plot right leg
        plot3d([handles.motion.jointX.estimated(15, index), handles.motion.jointX.estimated(13, index), handles.motion.jointX.estimated(11, index), handles.motion.jointX.estimated(9, index)], [handles.motion.jointY.estimated(15, index), handles.motion.jointY.estimated(13, index), handles.motion.jointY.estimated(11, index), handles.motion.jointY.estimated(9, index)], [handles.motion.jointZ.estimated(15, index), handles.motion.jointZ.estimated(13, index), handles.motion.jointZ.estimated(11, index), handles.motion.jointZ.estimated(9, index)], 'b');`

**Comment by wojtusch** [comment]
Thanks a lot for the feedback. This bug resulted from a restructuring of the data shortly before publication. It was fixed in commit [7db62b6](https://github.com/wojtusch/HuMoD/commit/7db62b6f10e9568ce13c227da8f6f8770ff71969).
