### ISSUE TITLE
force and kinematics synchronisation

### ISSUE THREAD

**Issue by charlotte-lemouel** [wojtusch/HuMoD#2]
Dear Janis Wojtusch,

I am using your Humod database for one of my current projects on estimating the body center of mass. I am using the raw data, and I noticed that there seems to be a time lag between the forces and the kinematics. In the accompanying documentation, you mention: "Raw motion and force data was synchronized by compensating temporal offset". Could you please tell me how this was done? In particular, which temporal offsets did you use for the running and hopping trials?

Best regards,

Charlotte Le Mouel

**Comment by wojtusch** [comment]
Thanks a lot for your interest in the HuMoD database. If you want to process the raw force measurements by yourself, you can find all relevant information in the file [ForceFilter.m](https://github.com/wojtusch/HuMoD/blob/master/ForceFilter.m).

The time lag between force and kinematic measurements was estimated through a separate series of measurements and modeled as linear function. Intercept and gradient of this linear function are given in lines 19 and 20. My implementation of the synchronization starts in line 89.

For compensating the offset and drift of the individual force sensors, I used the measurements of the unloaded force plates within the first and last ten seconds of each trial. Please refer to my implementation of the compensation starting in line 114 for more details.

Please make also sure to transform the reference frames of force and kinematic measurements into one common reference frame. For the HuMoD database, I used the instrumented treadmill as the global reference frame.

I hope this information helps you to prepare the measurements for your projects. All the best!

**Comment by wojtusch** [comment]
I have received feedback that the question has been answered.
